name: docu_fill
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1


environment:
  sdk: ^3.7.2

isar_version: &isar_version 3.1.8 # define the version to be used

dependencies:
  flutter:
    sdk: flutter
  #design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^16.0.0
  flutter_screenutil: ^5.9.3
  two_dimensional_scrollables: ^0.3.7
  adaptive_layout: ^0.1.7
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.0
  simple_loading_dialog: ^1.0.0
  #tools
  path: ^1.9.1
  path_provider: ^2.1.0
  docx_to_text: ^1.0.1
  file_picker: ^10.2.0
  xml: ^6.5.0
  archive: ^3.3.6
  #architec
  maac_mvvm_with_get_it: ^0.2.1+1
  maac_mvvm_annotation: ^0.0.2
  easy_localization: ^3.0.7+1
  json_annotation: ^4.7.0
  isar:
    version: *isar_version
    hosted: https://pub.isar-community.dev/
  isar_flutter_libs: # contains Isar Core
    version: *isar_version
    hosted: https://pub.isar-community.dev/

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  maac_mvvm_generator: ^0.0.3
  build_runner: ^2.5.4
  json_serializable: ^6.5.4
#  isar_generator:
#    version: *isar_version
#    hosted: https://pub.isar-community.dev/
  isar_generator:
    git:
      url: https://github.com/mdddj/isar
      ref: v3
      path: packages/isar_generator/
dependency_overrides:
  #source_gen: any
  #analyzer: any

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/images/png/
    - assets/images/svg/

